apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: django-app
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: app1
        image: 7724346/vanillayz:v0.1
        ports:
        - containerPort: 9000